// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    print(defaultTargetPlatform);
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBooVD2DjZURM4drnVRTLKESAObBfKTaZk',
    appId: '1:1059333987739:web:89759b9dcf7ed2aa01d53e',
    messagingSenderId: '1059333987739',
    projectId: 'ac-social-internship',
    authDomain: 'ac-social-internship.firebaseapp.com',
    storageBucket: 'ac-social-internship.appspot.com',
    measurementId: 'G-8R51JEQKS7',
  );

  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyClkoLfcLsvnc5mFuplVwYHxfisKkbkGsY',
  //   appId: '1:1059333987739:android:d3aedbfd873ea4b701d53e',
  //   messagingSenderId: '1059333987739',
  //   projectId: 'ac-social-internship',
  //   storageBucket: 'ac-social-internship.appspot.com',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKNvLPQs-9YWrjyRia4zK1Gk-M95yhXTA',
    appId: '1:235663151149:android:a754f7d8866d89914f28a4',
    messagingSenderId: '235663151149',
    projectId: 'order-app-91685',
    storageBucket: 'com.project.hungapp',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyBwr95DAcP6DB7oVYmI8slPGisbLIsiSdU',
  //   appId: '1:1059333987739:ios:dc96cb94e7d7d59f01d53e',
  //   messagingSenderId: '1059333987739',
  //   projectId: 'ac-social-internship',
  //   storageBucket: 'ac-social-internship.appspot.com',
  //   androidClientId: '1059333987739-94m9na8a1eka4hub72v6i38vgrkv5kun.apps.googleusercontent.com',
  //   iosClientId: '1059333987739-cpgh235lgmo3rm71k2h9vo3jonq81mfs.apps.googleusercontent.com',
  //   iosBundleId: 'com.project.socialapp.socialApp',
  // );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKNvLPQs-9YWrjyRia4zK1Gk-M95yhXTA',
    appId: '1:235663151149:ios:de220e40c72fb7e54f28a4',
    messagingSenderId: '235663151149',
    projectId: 'order-app-91685',
    storageBucket: 'ac-social-internship.appspot.com',
    androidClientId: '1059333987739-94m9na8a1eka4hub72v6i38vgrkv5kun.apps.googleusercontent.com',
    iosClientId: '1059333987739-cpgh235lgmo3rm71k2h9vo3jonq81mfs.apps.googleusercontent.com',
    iosBundleId: 'com.project.socialapp.socialApp',
  );
}
